<?php
/******************************************************************************
    
    Header of generated pages.

    @license    GPL
    @history    2021-03-15 18:30:30+01:00, Thierry Graff : Creation from former class headfoot
    @history    2021-02-27 23:05:44+01:00, Thierry Graff : Creation
********************************************************************************/
namespace observe\parts\page;

class header {
    
    public static function html(
        $pathToRoot  = '.',
        $title       = '',
        $description = '',
    ){
        $date = date('c');
        return <<<HTML
<!DOCTYPE html>
<!-- $date File generated by https://github.com/tig12/observe -->
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>$title</title>
    <meta name="description" content="$description">
    <link rel="shortcut icon" href="favicon.png" type="image/x-icon">
    <link rel="copyright" href="http://www.gnu.org/copyleft/gpl.html"/>
    <link rel="stylesheet" href="$pathToRoot/static/css/observe.css" type="text/css">
</head>

<body>

HTML;
    }
        
} // end class
