<?php
/******************************************************************************

    @license    GPL - conforms to file LICENCE located in root directory of current repository.
    @copyright  Thierry Graff
    @history    2026-03-12 00:42:19+01:00, Thierry Graff : Creation
********************************************************************************/

namespace observe\model;

use observe\app\ObserveException;
use observe\commands\observed;
use observe\commands\expected;
use observe\commands\stats;
use observe\commands\dim2;
use observe\commands\output;
use observe\commands\dev;
use tiglib\filesystem\mkdir;
use tigeph\model\IAA;

abstract class Study implements IStudy {
    
    /** Contents of the yaml command file located in config/  **/
    public readonly array $config;
    
    /** 
        @param  $studySlug Unique identifier of a study (entry "slug" in the yaml files in config/).
    **/
    public function __construct(string $studySlug){
        $this->config = Studies::getStudyConfig($studySlug);
        $this->checkStudyFile();
    }
    
    public function observed($params = []): string {
        return observed::execute($this, $params);
    }
    public function expected($params = []): string {
        return expected::execute($this, $params);
    }
    public function stats($params = []): string {
        return stats::execute($this, $params);
    }
    public function dim2($params = []): string {
        return dim2::execute($this, $params);
    }
    public function output($params = []): string {
        return output::execute($this, $params);
    }
    public function dev($params = []): string {
        return dev::execute($this, $params);
    }
    
    /**
        @return Error message if problem, empty message if ok.
    **/
    private function checkStudyFile(): void {
        $msg = '';
        if(!isset($this->config['slug'])){
            $msg .= "Missing entry \"slug\"\n";
        }
        //
        if(!isset($this->config['working-dir'])){
            $msg .= "Missing entry \"working-dir\"\n";
        }
        if(!is_dir($this->config['working-dir'])){
            mkdir::execute($this->config['working-dir']);
        }
        //
        if(!isset($this->config['out-dir'])){
            $msg .= "Missing entry \"out-dir\"\n";
        }
        if(!is_dir($this->config['out-dir'])){
            mkdir::execute($this->config['out-dir']);
        }
        //
        if(!isset($this->config['planets'])){
            $msg .= "Missing entry \"planets\"\n";
        }
        //
        if(!isset($this->config['dates'])){
            $msg .= "Missing entry \"dates\"\n";
        }
        if(($msg1 = IAA::checkCodes($this->config['planets'])) != ''){
            $msg .= $msg1;
        }
        //
        if($msg != ''){
            $msg = "INVALID STUDY FILE {$this->config['__study-file__']}\n" . trim($msg);
            throw new ObserveException($msg);
        }
    }
    
    /**
        Returns the array passed to header.html to build the navigation menu in output pages.
        The format is an associative array: [
            'href' => 'label',
        ]
    **/
    public function getNavigationArray(): array {
        $res = [
            '../../index.html'  => 'Observe home',
            'index.html'        => $this->config['output']['title'],
        ];
        foreach($this->config['dates'] as $date){
            $res["$date.html"] = ucfirst($date);
        }
        for($i=0; $i < count($this->config['dates']); $i++){
            for($j=$i+1; $j < count($this->config['dates']); $j++){
                $code = $this->config['dates'][$i] . '-' . $this->config['dates'][$j];
                $label = ucfirst($this->config['dates'][$i]) . ' - ' . ucfirst($this->config['dates'][$j]);
                $res ["$code.html"] =  $label;
            }
        }
        return $res;
    }
    
    /**
        Returns the root directory where the output is generated by command output.
    **/
    public function getOutputDirectory(): string {
        return $this->config['out-dir'];
    }
    
    /**
        Returns the directory where the images are generated by command output.
    **/
    public function getOutputImgDirectory(): string {
        return $this->config['out-dir'] . DS . 'img';
    }
    
    /**
        Returns the directory where the downloadable compressed csv files are generated by command output.
    **/
    public function getOutputCsvDirectory(): string {
        return $this->config['out-dir'] . DS . 'csv';
    }
    
    /**
        Returns the working directory containing the observed distributions of a study.
    **/
    public function getDatafile(): string {
        return $this->config['working-dir'] . DS . 'data.csv.bz2';
    }
    
    /**
        Returns the working directory containing the observed distributions of a study.
    **/
    public function getWorkingDirectory(): string {
        return $this->config['working-dir'];
    }
    
    /**
        Returns the directory containing the observed distributions of a study.
    **/
    public function getObservedDirectory(): string {
        return $this->config['working-dir'] . DS . 'observed';
    }
    
    /**
        Returns the directory containing the expected distributions of a study.
    **/
    public function getExpectedDirectory(): string {
        return $this->config['working-dir'] . DS . 'expected';
    }
    
    /**
        Returns the directory containing all the controls of a study.
    **/
    public function getControlsDirectory(): string {
        return $this->config['working-dir'] . DS . 'controls';
    }
    
    /**
        Returns the list of subdirectories of controls/ = the list of directories containing individual controls.
    **/
    public function getControlSubdirectories(): array {
        return glob($this->getControlsDirectory() . DS . 'control-*');
    }
    
    /**
        Returns an array containing the dates of a study, different from $dateName.
        @param      $dateName String like 'birth', 'death', 'mother' etc.
    **/
///////////// NOT USED YET /////////////////
    public function otherDates1(string $dateName): array {
        $res = [];
        foreach($this->config['dates'] as $date){
            if($date != $dateName){
                $res[] = $date;
            }
        }
        return $res;
    }
    
    /**
        Returns an array containing the possible combinations of 2 dates of a study, different from $dateName.
        @param  $dateName String like 'mother-father'
        @return     Ex: ['child-father', 'child-mother', 'child-wedding', 'mother-wedding', 'father-wedding']
    **/
///////////// NOT USED YET /////////////////
    public function otherDates2(string $dateName) {
        // TODO Implement
        return [];
    }
    
} // end class
