<?php
/******************************************************************************
    
    Manipulate statistical informations of distributions read from a file stats.csv,
    generated with php run-observe.php <study> stats <split>
    
    Arrays manipulated by StatsDistrib have the fields of self::STATS_CSV_FIELDS
    This array is noted <StatsDistrib>
    
    StatsDistrib provides informations for distributions of type distrib1 and distrib2,
    in a directory containing stats.csv generated by php run-observe.php <study> stats <split>
    
    The <StatsDistrib> of the distributions (returned by self::loadStats()) are stored on an array with this structure:
        [
          'birth' => [
            'day' => <StatsDistrib>
            'year' => <StatsDistrib>
            'planets' => [ 'SO' => <StatsDistrib>, 'MO' =>   ...   ]
            'aspects' => [ 'SO-MO' => <StatsDistrib>, 'SO-ME' =>   ... ]
          'birth-death' => [
            'age' => <StatsDistrib>
            'interaspects' => [ 'SO-SO' => <StatsDistrib>, 'SO-MO' =>   ... ]
        ]
        
    
    @license    GPL - conforms to file LICENCE located in root directory of current repository.
    @copyright  Thierry Graff
    
    @history    2026-04-10 11:53:03+01:00, Thierry Graff : Creation
********************************************************************************/

namespace observe\model\distrib;

use observe\model\Observe;
use observe\model\Studies;
use tiglib\arrays\csvAssociative;

class StatsDistrib {
    
    /** 
        Column names of files stats.csv.
        Unique reference for the names and the order.
    **/
    const array STATS_CSV_FIELDS = [
        // id of the distrib
        'DATE_NAME',
        'DISTRIB_TYPE',
        'DISTRIB',
        // statistical infos
        'FROM',
        'TO',
        'MIN_KEY',
        'MIN',
        'MAX_KEY',
        'MAX',
        'MEAN',
        'SIGMA',
        'CHI2',
        'P',
        'P_LIMIT',
    ];
    
    /**
        Loads statistical informations of distributions from file stats.csv.
        @param  $dir    Path to a directory containing a file called stats.csv.
    **/
    public static function loadStats(string $dir): array {
        $lines = csvAssociative::compute($dir . DS . 'stats.csv', Observe::CSV_SEP);
        $res = [];
        foreach($lines as $line){
            if(!isset($res[$line['DATE_NAME']])){
                $res[$line['DATE_NAME']] = [];
            }
            if(!isset($res[$line['DATE_NAME']][$line['DISTRIB_TYPE']])){
                $res[$line['DATE_NAME']][$line['DISTRIB_TYPE']] = [];
            }
            $line2 = $line; // $line2 contains only statistical informations, no keys.
            unset($line2['DATE_NAME']);
            unset($line2['DISTRIB_TYPE']);
            unset($line2['DISTRIB']);
            if($line['DISTRIB'] == ''){
                // day, year, age
                $res[$line['DATE_NAME']][$line['DISTRIB_TYPE']] = $line2;
            }
            else{
                // planets, aspects, interaspects
                $res[$line['DATE_NAME']][$line['DISTRIB_TYPE']][$line['DISTRIB']] = $line2;
            }
        }
        return $res;
    }
    
} // end class
