<?php
/******************************************************************************

    Code to generate the html pages in output/
    Called by commands/output.php
    
    Example of call: php run-observe.php death-fr output page distrib1

    @license    GPL - conforms to file LICENCE located in root directory of current repository.
    @copyright  Thierry Graff
    
    @history    2026-04-10 14:55:19+01:00, Thierry Graff : Refactor
    @history    2026-04-09 10:23:25+01:00, Thierry Graff : Creation from a split of output.php
********************************************************************************/

namespace observe\commands\output;

use observe\model\IStudy;
use observe\model\distrib\StatsDistrib;
use observe\model\PlanetCode;
use tiglib\filesystem\mkdir;
use tiglib\filesystem\file_put_contents;
use tigeph\model\IAA;

class output_page {
    
    const array POSSIBLE_WHAT = [
        'all'           => 'Generate pages "index", "distrib1" and "distrib2"',
        'index'         => 'Generate home page of the study output',
        'distrib1'      => 'Generate distributions of type distrib1',
        'distrib2'      => 'Generate distributions of type distrib2',
        'gallery'      => 'Gallery of distributions',
    ];

    const string FOOTER = 'Page generated by <i>observe</i> program - '
        . 'Code repository: <a href="https://github.com/tig12/observe">github.com/tig12/observe</a> - '
        . 'Documentation: <a href="https://tig12.github.io/observe">tig12.github.io/observe</a>';
    
    /**
        Called by output::execute()
        
        @param  $params are parameters passed to command output, so $params[0] = 'page'.
        @return Error message or empty string if ok.
    **/
    public static function execute(IStudy $study, array $params): string {
        if(!in_array($params[1], array_keys(self::POSSIBLE_WHAT))){
            return "INVALID PARAMETER object: \"{$params[1]}\".";
        }
        $what = $params[1];
        // ****** WARNING Temporary code ******
        $echoMessage = true; // concerns filename creation
        // ****** END WARNING ******
        
        switch($what){
            case 'index':       self::generateIndex($study); break;
            case 'distrib1':    self::generateDistrib1($study); break;
            case 'distrib2':    self::generateDistrib2($study); break;
            case 'gallery':     self::generateGallery($study); break;
            case 'all':
                self::generateIndex($study);
                self::generateDistrib1($study);
                self::generateDistrib2($study);
                self::generateGallery($study);
            break;
        }
        return '';
    }
    
    /**
        Computes a html page using variables stored in $V.
        @param  $template, relative to observe root directory
        @param  $V View variable
    **/
    public static function template(string $template, array $V): string {
        $filename = __DIR__ . DS . 'templates' . DS . $template;
        ob_start();
        include $filename;
        $res = ob_get_contents();
        ob_end_clean();
        return $res;
    }
    
    /**
        Generates the beginning of a page
        @param  $V View variable
    **/
    public static function header(array $V): string {
        return self::template('header.html', $V);
    }
    
    /**
        Generates the end of a page
        @param  $V View variable
    **/
    public static function footer(array $V): string {
        return self::template('footer.html', $V);
    }
    
    /** 
        Generates and stores the home page of a given study.
    **/
    private static function generateIndex(IStudy $study): void {
        $res = '';
        //
        $V = [
            'path-to-root' => '../..',
            'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
            'title' => $study->config['output']['title'],
            'subtitle' => $study->config['output']['subtitle'] ?? '',
            'description' => $study->config['output']['description'] ?? '',
            'intro' => $study->config['output']['intro'] ?? '',
            'navigation' => $study->getNavigationArray(),
        ];
        $res .= self::header($V);
        //
        $stats_obs = StatsDistrib::loadStats($study->getObservedDirectory());
        $V = [
            'dates' => $study->config['dates'],
            'planets' => $study->config['planets'],
            'stats-obs' => $stats_obs,
        ];
        $res .= self::template('index.html', $V);
        //
        $V = ['text' => self::FOOTER];
        $res .= self::footer($V);
        //
        $outDir = $study->getOutputDirectory();
        mkdir::execute($outDir);
        $outFilename = $outDir . DS . 'index.html'; // ex: output/studies/death-fr/index.html
        file_put_contents::execute($outFilename, $res);
    }
    
    /** 
        Generates the pages of type distrib1 (distributions of a single date)
    **/
    private static function generateDistrib1(IStudy $study): void {
        
        $stats_obs = StatsDistrib::loadStats($study->getObservedDirectory());
        $stats_exp = StatsDistrib::loadStats($study->getExpectedDirectory());
        
        foreach($study->config['dates'] as $dateName){
            $res = '';
            //
            $V = [
                'path-to-root' => '../..',
                'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
                'title' => ucFirst($dateName),
                'subtitle' => $study->config['output']['title'] ?? '',
                'description' => '',
                'intro' => '',
                'navigation' => $study->getNavigationArray(),
            ];
            $res .= self::header($V);
            //
            $V = [
                'date-name' => $dateName,
                'date-label' => ucFirst($dateName),
                //'other-dates' => $study->otherDates1(),
                'planets' => $study->config['planets'],
                'stats-obs' => $stats_obs[$dateName],
                'stats-exp' => $stats_exp[$dateName],
            ];
            $res .= self::template('distrib1.html', $V);
            //
            $V = ['text' => self::FOOTER];
            $res .= self::footer($V);
            //
            $outDir = $study->getOutputDirectory();
            mkdir::execute($outDir);
            $outFilename = $outDir . DS . $dateName . '.html'; // ex: output/studies/death-fr/birth.html
            file_put_contents::execute($outFilename, $res);
        }
    }
    
    /** 
        Generates the pages of type distrib2 (distributions between 2 dates)
    **/
    private static function generateDistrib2(IStudy $study): void {

        $stats_obs = StatsDistrib::loadStats($study->getObservedDirectory());
        $stats_exp = StatsDistrib::loadStats($study->getExpectedDirectory());
        
        $nDates = count($study->config['dates']);
        for($i=0; $i < $nDates; $i++){
            for($j=$i+1; $j < $nDates; $j++){
                $dateName = $study->config['dates'][$i] . '-' . $study->config['dates'][$j]; // ex: birth-death
                $dateTitle = ucfirst($study->config['dates'][$i]) . ' - ' . ucFirst($study->config['dates'][$j]);
                $res = '';
                //
                $V = [
                    'path-to-root' => '../..',
                    'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
                    'title' => ucFirst($dateName),
                    'subtitle' => $study->config['output']['title'] ?? '',
                    'description' => '',
                    'intro' => '',
                    'navigation' => $study->getNavigationArray(),
                ];
                $res .= self::header($V);
                //
                $V = [
                    'date-name' => $dateName,
                    'date-labels' => [ $study->config['dates'][$i], $study->config['dates'][$j] ],
                    'planets' => $study->config['planets'],
                    'stats-obs' => $stats_obs[$dateName],
                    'stats-exp' => $stats_exp[$dateName],
                ];
                $res .= self::template('distrib2.html', $V);
                //
                $V = ['text' => self::FOOTER];
                $res .= self::footer($V);
                //
                $outDir = $study->getOutputDirectory();
                mkdir::execute($outDir);
                $outFilename = $outDir . DS . $dateName . '.html'; // ex: output/studies/death-fr/birth-death.html
                file_put_contents::execute($outFilename, $res);
            } // end loop on $j
        } // end loop on $i
    }
    
    /** 
        Generates a gallery of images
    **/
    private static function generateGallery(IStudy $study): void {
        $res = '';
        //
        $title = $study->config['output']['title'] ?? '';
        $V = [
            'path-to-root' => '../..',
            'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
            'title' => "Gallery",
            'subtitle' => $title,
            'description' => "Gallery of images from $title",
            'intro' => '',
            'navigation' => $study->getNavigationArray(),
        ];
        $res .= self::header($V);
        //
        $V = [];
        $V['planet-names'] = IAA::getNames($study->config['planets']);
        $V['date-names'] = $study->config['dates'];
        // table of contents
        $V['toc-same'] = [];
        $V['toc-all-no-planets'] = [];
        $V['toc-all-planets'] = [];
        // Paragraphs "same planets"
        $V['same'] = [];
        // Paragraphs "all distributions of planets"
        $V['all-planets-h3'] = [];      // id of h3 = local href in toc
        $V['all-planets-titles'] = [];  // horizontal th of the table
        $V['all-planets-cells'] = [];   // td
        //
        // Same planets
        //
        for($i=0; $i < count($study->config['dates']); $i++){
            for($j=$i+1; $j < count($study->config['dates']); $j++){
                $dateName1 = $study->config['dates'][$i];
                $dateName2 = $study->config['dates'][$j];
                $dateName = "$dateName1-$dateName2"; // ex: birth-death
                $label = ucFirst($dateName1) . ' - ' . ucFirst($dateName2);
                $h3_id = "same-planets-$dateName";
                $V['toc-same'][] = [
                    'url' => $h3_id,
                    'label' => $label,
                ];
                $V['same'][$dateName] = [
                    'h3-id' => $h3_id,
                    'h3-label' => $label,
                    'contents' => [],
                ];
                foreach($study->config['planets'] as $planet){
                    $planetName = IAA::PLANET_NAMES[$planet];
                    $code = "$planet-$planet";
                    $label = "$planetName $dateName1 - $planetName $dateName2";
                    $V['same'][$dateName]['contents'][] = [
                        'label'         => $label,
                        'img-url'       => "img/$dateName/interaspects/dim2/$code.png",
                        'img-alt'       => "Positions of $label",
                        'details-url'   => "$dateName.html#relations-planets-$code",
                    ];
                }
            }
        }
        //
        // All distributions of age, day, year
        //
        $V['toc-all-no-planets']['day'] = [
            'url' => 'all-day',
            'label' => 'Day',
        ];
        $V['toc-all-no-planets']['year'] = [
            'url' => 'all-year',
            'label' => 'Year',
        ];
        $V['toc-all-no-planets']['age'] = [
            'url' => 'all-age',
            'label' => 'Age',
        ];
        //
        // All distributions of planets
        //
        // column titles
        for($i=0; $i < count($study->config['dates']); $i++){
            $V['all-planets-titles'][] = 'Aspects ' . $study->config['dates'][$i];
        }
        for($i=0; $i < count($study->config['dates']); $i++){
            $dateName1 = $study->config['dates'][$i];
            for($j=$i+1; $j < count($study->config['dates']); $j++){
                $dateName2 = $study->config['dates'][$j];
                $dateName = "$dateName1-$dateName2"; // ex: birth-death
                $V['all-planets-titles'][] = "Interaspects $dateName1 - $dateName2";
                $V['all-planets-titles'][] = "Interaspects $dateName2 - $dateName1";
            }
        }
        // cells
        foreach($study->config['planets'] as $planet1){
            $planetName1 = IAA::PLANET_NAMES[$planet1];
            $label = "Same planets, $dateName1 - $dateName2";
            $h3_id = "all-planets-$planet1";
            $V['toc-all-planets'][] = [
                'url' => $h3_id,
                'label' => $planetName1,
            ];
            $V['all-planets-h3'][$planet1] = [
                'id' => $h3_id,
                'label' => $planetName1,
            ];
            $V['all-planets-cells'][$planet1] = [];
            foreach($study->config['planets'] as $planet2){
                $V['all-planets-cells'][$planet1][$planet2] = [];
            }
            // aspects - ex birth - birth and death - death
            for($i=0; $i < count($study->config['dates']); $i++){
                $dateName = $study->config['dates'][$i];
                foreach($study->config['planets'] as $planet2){
                    $planetName2 = IAA::PLANET_NAMES[$planet2];
                    if($planet1 == $planet2){
                        // no aspect between a planet and itself - but a void cell
                        $V['all-planets-cells'][$planet1][$planet2][] = [];
                        continue;
                    }
                    $code = PlanetCode::pairCode($planet1, $planet2, $study->config['planets']);
                    $label = "$planetName1 $dateName - $planetName2 $dateName";
                    $V['all-planets-cells'][$planet1][$planet2][] = [
                        'label'         => $label,
                        'img-url'       => "img/$dateName/aspects/dim2/$code.png",
                        'img-alt'       => "Distribution of aspects $label",
                        'details-url'   => "$dateName.html#aspect-$code",
                    ];
                }
            }
            // interaspects
            for($i=0; $i < count($study->config['dates']); $i++){
                $dateName1 = $study->config['dates'][$i];
                for($j=$i+1; $j < count($study->config['dates']); $j++){
                    $dateName2 = $study->config['dates'][$j];
                    $dateName = "$dateName1-$dateName2"; // ex: birth-death
                    // Respect the date order - ex birth-death
                    foreach($study->config['planets'] as $planet2){
                        $planetName2 = IAA::PLANET_NAMES[$planet2];
                        $code = "$planet1-$planet2";
                        $label = "$planetName1 $dateName1 - $planetName2 $dateName2";
                        $V['all-planets-cells'][$planet1][$planet2][] = [
                            'label'         => $label,
                            'img-url'       => "img/$dateName/interaspects/dim2/$code.png",
                            'img-alt'       => "Positions of $label",
                            'details-url'   => "$dateName.html#relations-planets-$code",
                        ];
                    }
                    // Invert the date order - ex death-birth
                    foreach($study->config['planets'] as $planet2){
                        $planetName2 = IAA::PLANET_NAMES[$planet2];
                        $code = "$planet2-$planet1"; // here inversion
                        $label = "$planetName1 $dateName2 - $planetName2 $dateName1"; // here inversion
                        $V['all-planets-cells'][$planet1][$planet2][] = [
                            'label'         => $label,
                            'img-url'       => "img/$dateName/interaspects/dim2/$code.png",
                            'img-alt'       => "Positions of $label",
                            'details-url'   => "$dateName.html#relations-planets-$code",
                        ];
                    }
                }
            }
        } // end loop on planet1
        //
        $res .= self::template('gallery.html', $V);
        //
        $V = ['text' => self::FOOTER];
        $res .= self::footer($V);
        //
        $outFilename = $study->getOutputDirectory() . DS . 'gallery.html'; // ex: output/studies/death-fr/gallery.html
        file_put_contents::execute($outFilename, $res);
    }
    
} // end class
