<?php
/******************************************************************************

    Code to generate the html pages in output/
    Called by commands/output.php
    
    Example of call: php run-observe.php death-fr output page distrib1

    @license    GPL - conforms to file LICENCE located in root directory of current repository.
    @copyright  Thierry Graff
    
    @history    2026-04-10 14:55:19+01:00, Thierry Graff : Refactor
    @history    2026-04-09 10:23:25+01:00, Thierry Graff : Creation from a split of output.php
********************************************************************************/

namespace observe\commands\output;

use observe\model\IStudy;
use observe\model\distrib\StatsDistrib;
use tiglib\filesystem\mkdir;
use tiglib\filesystem\file_put_contents;

class output_page {
    
    const array POSSIBLE_WHAT = [
        'all'           => 'Generate pages "index", "distrib1" and "distrib2"',
        'index'         => 'Generate home page of the study output',
        'distrib1'      => 'Generate distributions of type distrib1',
        'distrib2'      => 'Generate distributions of type distrib2',
        'gallery'      => 'Gallery of distributions',
    ];

    const string FOOTER = 'Page generated by <i>observe</i> program - '
        . 'Code repository: <a href="https://github.com/tig12/observe">github.com/tig12/observe</a> - '
        . 'Documentation: <a href="https://tig12.github.io/observe">tig12.github.io/observe</a>';
    
    /**
        Called by output::execute()
        
        @param  $params are parameters passed to command output, so $params[0] = 'page'.
        @return Error message or empty string if ok.
    **/
    public static function execute(IStudy $study, array $params): string {
        if(!in_array($params[1], array_keys(self::POSSIBLE_WHAT))){
            return "INVALID PARAMETER object: \"{$params[1]}\".";
        }
        $what = $params[1];
        // ****** WARNING Temporary code ******
        $echoMessage = true; // concerns filename creation
        // ****** END WARNING ******
        
        switch($what){
            case 'index':       self::generateIndex($study); break;
            case 'distrib1':    self::generateDistrib1($study); break;
            case 'distrib2':    self::generateDistrib2($study); break;
            case 'gallery':     self::generateGallery($study); break;
            case 'all':
                self::generateIndex($study);
                self::generateDistrib1($study);
                self::generateDistrib2($study);
                self::generateGallery($study);
            break;
        }
        return '';
    }
    
    /**
        Computes a html page using variables stored in $V.
        @param  $template, relative to observe root directory
        @param  $V View variable
    **/
    public static function template(string $template, array $V): string {
        $filename = __DIR__ . DS . 'templates' . DS . $template;
        ob_start();
        include $filename;
        $res = ob_get_contents();
        ob_end_clean();
        return $res;
    }
    
    /**
        Generates the beginning of a page
        @param  $V View variable
    **/
    public static function header(array $V): string {
        return self::template('header.html', $V);
    }
    
    /**
        Generates the end of a page
        @param  $V View variable
    **/
    public static function footer(array $V): string {
        return self::template('footer.html', $V);
    }
    
    /** 
        Generates and stores the home page of a given study.
    **/
    private static function generateIndex(IStudy $study): void {
        $res = '';
        //
        $V = [
            'path-to-root' => '../..',
            'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
            'title' => $study->config['output']['title'],
            'subtitle' => $study->config['output']['subtitle'] ?? '',
            'description' => $study->config['output']['description'] ?? '',
            'intro' => $study->config['output']['intro'] ?? '',
            'navigation' => $study->getNavigationArray(),
        ];
        $res .= self::header($V);
        //
        $stats_obs = StatsDistrib::loadStats($study->getObservedDirectory());
        $V = [
            'dates' => $study->config['dates'],
            'planets' => $study->config['planets'],
            'stats-obs' => $stats_obs,
        ];
        $res .= self::template('index.html', $V);
        //
        $V = [];
        $res .= self::footer($V);
        //
        $outDir = $study->getOutputDirectory();
        mkdir::execute($outDir);
        $outFilename = $outDir . DS . 'index.html'; // ex: output/studies/death-fr/index.html
        file_put_contents::execute($outFilename, $res);
    }
    
    /** 
        Generates the pages of type distrib1 (distributions of a single date)
    **/
    private static function generateDistrib1(IStudy $study): void {
        
        $stats_obs = StatsDistrib::loadStats($study->getObservedDirectory());
        $stats_exp = StatsDistrib::loadStats($study->getExpectedDirectory());
        
        foreach($study->config['dates'] as $dateName){
            $res = '';
            //
            $V = [
                'path-to-root' => '../..',
                'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
                'title' => ucFirst($dateName),
                'subtitle' => $study->config['output']['title'] ?? '',
                'description' => '',
                'intro' => '',
                'navigation' => $study->getNavigationArray(),
            ];
            $res .= self::header($V);
            //
            $V = [
                'date-name' => $dateName,
                'date-label' => ucFirst($dateName),
                //'other-dates' => $study->otherDates1(),
                'planets' => $study->config['planets'],
                'stats-obs' => $stats_obs[$dateName],
                'stats-exp' => $stats_exp[$dateName],
            ];
            $res .= self::template('distrib1.html', $V);
            //
            $V = ['text' => self::FOOTER];
            $res .= self::footer($V);
            //
            $outDir = $study->getOutputDirectory();
            mkdir::execute($outDir);
            $outFilename = $outDir . DS . $dateName . '.html'; // ex: output/studies/death-fr/birth.html
            file_put_contents::execute($outFilename, $res);
        }
    }
    
    /** 
        Generates the pages of type distrib2 (distributions between 2 dates)
    **/
    private static function generateDistrib2(IStudy $study): void {

        $stats_obs = StatsDistrib::loadStats($study->getObservedDirectory());
        $stats_exp = StatsDistrib::loadStats($study->getExpectedDirectory());
        
        $nDates = count($study->config['dates']);
        for($i=0; $i < $nDates; $i++){
            for($j=$i+1; $j < $nDates; $j++){
                $dateName = $study->config['dates'][$i] . '-' . $study->config['dates'][$j]; // ex: birth-death
                $dateTitle = ucfirst($study->config['dates'][$i]) . ' - ' . ucFirst($study->config['dates'][$j]);
                $res = '';
                //
                $V = [
                    'path-to-root' => '../..',
                    'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
                    'title' => ucFirst($dateName),
                    'subtitle' => $study->config['output']['title'] ?? '',
                    'description' => '',
                    'intro' => '',
                    'navigation' => $study->getNavigationArray(),
                ];
                $res .= self::header($V);
                //
                $V = [
                    'date-name' => $dateName,
                    'date-labels' => [ $study->config['dates'][$i], $study->config['dates'][$j] ],
                    'planets' => $study->config['planets'],
                    'stats-obs' => $stats_obs[$dateName],
                    'stats-exp' => $stats_exp[$dateName],
                ];
                $res .= self::template('distrib2.html', $V);
                //
                $V = ['text' => self::FOOTER];
                $res .= self::footer($V);
                //
                $outDir = $study->getOutputDirectory();
                mkdir::execute($outDir);
                $outFilename = $outDir . DS . $dateName . '.html'; // ex: output/studies/death-fr/birth-death.html
                file_put_contents::execute($outFilename, $res);
            } // end loop on $j
        } // end loop on $i
    }
    
    /** 
        Generates a gallery of images
    **/
    private static function generateGallery(IStudy $study): void {
        $res = '';
        //
        $V = [
            'path-to-root' => '../..',
            'date' => new \Datetime('now')->format('Y-m-d h:i:s'),
            'title' => "Gallery",
            'subtitle' => $study->config['output']['title'] ?? '',
            'description' => 'At person death, the planets are more often',
            'intro' => '',
            'navigation' => $study->getNavigationArray(),
        ];
        $res .= self::header($V);
        //
        $V = [
            'dates' => $study->config['dates'],
            'planets' => $study->config['planets'],
        ];
        $res .= self::template('gallery.html', $V);
        //
        $V = ['text' => self::FOOTER];
        $res .= self::footer($V);
        //
        $outFilename = $study->getOutputDirectory() . DS . 'gallery.html'; // ex: output/studies/death-fr/gallery.html
        file_put_contents::execute($outFilename, $res);
    }
    
} // end class
